version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.13.0

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install

jobs:
  build:
    executor: node
    steps:
      - setup
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build

  release:
    executor: node
    steps:
      - setup
      - run:
          name: Build
          command: yarn build
      - run:
          name: Create a new release
          command: npx semantic-release

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
